### ISSUE TITLE
Show the recent build in the UI

### ISSUE THREAD

**Issue by SimonMonecke** [flosell/lambdacd#58]
If you open the UI you always see the build number 1.
It would be nice if LambdaCD shows the recent build.

**Comment by flosell** [comment]
This should be fixed in #51, released in version 0.5.4. 
Feel free to re-open that issue if that doesn't work.

**Comment by SimonMonecke** [comment]
We still have the same error after updating to lambdacd 0.5.4 and clojure 1.7.0
